{% set name = "gars_field" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f889ab5fb12c2a8466201436d0ee9907a58e99112c2414af05b149cf1d1be2a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - shapely
    - pyproj >=3.0.0

test:
  imports:
    - gars_field

about:
  home: https://github.com/corteva/gars-field
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Toolkit to generate Global Area Reference System grids.
  description: |
    Toolkit to generate Global Area Reference System grids. 
  doc_url: https://github.com/corteva/gars-field
  dev_url: https://github.com/corteva/gars-field

extra:
  recipe-maintainers:
    - snowman2
